version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: greenmate_postgres
    environment:
      POSTGRES_DB: greenmate
      POSTGRES_USER: greenmate_user
      POSTGRES_PASSWORD: greenmate_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: greenmate_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Adminer for database management (optional)
  adminer:
    image: adminer:4
    container_name: greenmate_adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: